version: "3.9"
services:
  postgres-test:
    image: postgres:17
    container_name: postgres-test
    environment:
      POSTGRES_DB: portfolio_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d portfolio_test"]
      interval: 10s
      timeout: 5s
      retries: 5